# Generated by Django 5.2.17 on 2026-10-05 10:56

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ModelProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Unique user-friendly name for this profile.', max_length=128, unique=True)),
                ('provider', models.CharField(choices=[('nvidia', 'NVIDIA NIM'), ('ollama', 'Ollama'), ('openai_compatible', 'OpenAI-compatible'), ('mock', 'Mock (Offline Testing)')], db_index=True, help_text='Inference provider type.', max_length=64)),
                ('endpoint', models.CharField(blank=True, default='', help_text='API endpoint base URL (e.g. https://integrate.api.nvidia.com/v1 or http://localhost:11434).', max_length=512)),
                ('model', models.CharField(help_text='Model identifier (e.g. nvidia/nemotron-3-ultra-550b-a55b, llama3.1:8b, Qwen).', max_length=256)),
                ('api_key', models.CharField(blank=True, default='', help_text='API key or token for provider authentication. Never exposed via API reads.', max_length=512)),
                ('timeout', models.FloatField(default=30.0, help_text='Request timeout in seconds.')),
                ('temperature', models.FloatField(blank=True, help_text='Sampling temperature between 0.0 and 2.0.', null=True)),
                ('max_tokens', models.PositiveIntegerField(blank=True, help_text='Maximum tokens to generate.', null=True)),
                ('capabilities', models.JSONField(blank=True, default=list, help_text='List of supported capabilities (generation, streaming, structured_output).')),
                ('extra_config', models.JSONField(blank=True, default=dict, help_text='Additional provider-specific parameters.')),
                ('is_active', models.BooleanField(db_index=True, default=False, help_text='Whether this profile is currently active as the research model.')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-is_active', 'name'],
                'indexes': [models.Index(fields=['is_active', '-created_at'], name='gateway_mod_is_acti_bdac92_idx'), models.Index(fields=['provider', 'name'], name='gateway_mod_provide_a3fb18_idx')],
            },
        ),
    ]
