# Generated by Django 5.2.17 on 2026-10-02 06:50

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ResearchRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('objective', models.TextField(help_text='User-provided research objective.')),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], db_index=True, default='queued', max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('duration_ms', models.FloatField(blank=True, help_text='Total execution duration in milliseconds.', null=True)),
                ('result', models.JSONField(blank=True, default=dict, help_text='Structured result dictionary from ResearchResult.to_dict().')),
                ('error_message', models.TextField(blank=True, default='', help_text='Sanitized error description if status is failed or cancelled.')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', '-created_at'], name='agent_resea_status_a61c72_idx')],
            },
        ),
    ]
