# Generated by Django 5.2.17 on 2026-10-02 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='researchrun',
            name='mode',
            field=models.CharField(choices=[('model_knowledge', 'Model Knowledge'), ('knowledge_base', 'Knowledge Base'), ('web', 'Web'), ('web_knowledge_base', 'Web + Knowledge Base')], db_index=True, default='knowledge_base', help_text='Information source mode for this research run.', max_length=32),
        ),
        migrations.AddIndex(
            model_name='researchrun',
            index=models.Index(fields=['mode', '-created_at'], name='agent_resea_mode_1942a3_idx'),
        ),
    ]
