# Generated by Django 5.2.17 on 2026-10-05 10:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0002_researchrun_mode_and_more'),
        ('gateway', '0002_bootstrap_default_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='researchrun',
            name='model_name',
            field=models.CharField(blank=True, default='', help_text='Snapshot of model identifier used for execution.', max_length=256),
        ),
        migrations.AddField(
            model_name='researchrun',
            name='model_profile',
            field=models.ForeignKey(blank=True, help_text='ModelProfile configured for this research run.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='research_runs', to='gateway.modelprofile'),
        ),
        migrations.AddField(
            model_name='researchrun',
            name='provider_name',
            field=models.CharField(blank=True, default='', help_text='Snapshot of provider type used for execution.', max_length=64),
        ),
    ]
