# Generated by Django 5.2.17 on 2026-09-21 13:12

import django.db.models.deletion
import pgvector.django.vector
import uuid
from django.db import migrations, models
from pgvector.django import VectorExtension


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        # Enable the pgvector extension in PostgreSQL before creating vector columns.
        # This will fail clearly if the PostgreSQL server does not have pgvector installed.
        VectorExtension(),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=512)),
                ('content', models.TextField(help_text='Full source text of the document.')),
                ('source', models.CharField(blank=True, default='', help_text='Origin of the document (file path, URL, etc.).', max_length=1024)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('ready', 'Ready'), ('error', 'Error')], db_index=True, default='pending', max_length=20)),
                ('error_message', models.TextField(blank=True, default='', help_text="Error details if status is 'error'.")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DocumentChunk',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('content', models.TextField(help_text='Text content of this chunk.')),
                ('chunk_index', models.IntegerField(help_text='Position of this chunk within the source document (0-based).')),
                ('start_offset', models.IntegerField(help_text='Character offset where this chunk starts in the source document.')),
                ('end_offset', models.IntegerField(help_text='Character offset where this chunk ends in the source document.')),
                ('embedding', pgvector.django.vector.VectorField(dimensions=384, help_text='Embedding vector for similarity search.')),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chunks', to='rag.document')),
            ],
            options={
                'ordering': ['document', 'chunk_index'],
                'indexes': [models.Index(fields=['document', 'chunk_index'], name='rag_documen_documen_637082_idx')],
            },
        ),
    ]
